# This is necessary until https://github.com/travis-ci/travis-ci/issues/3120 is
# fixed
sudo: required

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.10.5
  - 2.11.7

jdk:
  - openjdk7
  - oraclejdk7
  # Note: not currently testing on JDK 8 internally
  - oraclejdk8

before_script:
  # default $SBT_OPTS is irrelevant to sbt launcher
  - unset SBT_OPTS
  - ./bin/travisci
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION update

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test && ./sbt coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
