language: scala

scala:
  - 2.10.5
  - 2.11.7

jdk:
  - openjdk7
  - oraclejdk7
  # Note: not currently testing on JDK 8 internally
  - oraclejdk8

script:
  - travis_retry sbt -J-Xss8M -J-Xms512M -J-Xmx2G ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - bash <(curl -s https://codecov.io/bash)
