url: https://twitter.github.io/finatra
title: Finatra
subtitle: Fast, testable, Scala services built on TwitterServer and Finagle.
author: Twitter
simple_search: https://www.google.com/search
description: Fast, testable, Scala services built on TwitterServer and Finagle.
# Default date format is "ordinal" (resulting in "July 22nd 2007")
date_format: "ordinal"
# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /finatra/atom.xml
# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /finatra
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public/finatra
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb
paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
titlecase: true       # Converts page and post titles to titlecase
